from django.db import models

class Movie(models.Model):
    # Primary key (auto-generated by Django if not specified)
    movie_id = models.AutoField(primary_key=True)
    
    # Fields
    title = models.CharField(max_length=100)
    director = models.CharField(max_length=100)
    release_year = models.IntegerField()
    genre = models.CharField(max_length=50)
    rating = models.FloatField()

    def __str__(self):
        return f"{self.title} ({self.release_year})"
